import uuid
from dataclasses import fields, asdict
from core.database import DatabaseManager
from stats.chunking import ChunkingStats
from stats.models import PlayerStatsDocument


class IngestionManager:
    database_manager: DatabaseManager
    chunker: ChunkingStats

    def __init__(self, **data):
        super().__init__(**data)
        self.database_manager = DatabaseManager()
        self.chunker = ChunkingStats()

    def ingest_player_stats(self, stats_data: list[dict]):
        if not self.database_manager.connection:
            self.database_manager.connect()
        cursor = self.database_manager.connection.cursor()

        # Map source dict keys to model field names
        field_mapping = {
            "player_display_name": "player_name",
        }

        # Get valid field names from PlayerStatsDocument
        valid_fields = {field.name for field in fields(PlayerStatsDocument)}

        for stat in stats_data:
            try:
                print(f"Ingesting stat for player {stat['player_display_name']}...")
                # Transform the dict and unpack it
                stat_mapped = {field_mapping.get(k, k): v for k, v in stat.items()}
                # Filter to only include fields that exist in PlayerStatsDocument
                stat_filtered = {k: v for k, v in stat_mapped.items() if k in valid_fields}

                # Generate content and embedding first
                content = self.chunker.chunk_stat(stat, chunk_size=500)
                if not content:
                    print(
                        f"Skipping stat for player {stat['player_display_name']} due to insufficient data."
                    )
                    continue
                print(f"Generated content for player {stat['player_display_name']}: {content[:100]}...")
                embedding = self.database_manager.embedding_model.encode(content)

                # Create player document with all required fields
                player: PlayerStatsDocument = PlayerStatsDocument(
                    content=content,
                    embedding=embedding,
                    **stat_filtered
                )
                print(f"Generated embedding for player {stat['player_display_name']}.")
                player_dict = asdict(player)
                # Exclude 'id' field as it's auto-generated by the database
                player_dict.pop('id', None)
                columns = ", ".join(player_dict.keys())
                placeholders = ", ".join(["%s"] * len(player_dict))
                values = tuple(player_dict.values())
                cursor.execute(
                    f"INSERT INTO player_stats_documents ({columns}) VALUES ({placeholders})",
                    values,
                )
                print(f"Inserted stat for player {stat['player_display_name']} into database.")
            except Exception as e:
                self.database_manager.connection.rollback()
                print(
                    f"Error ingesting stat for player {stat['player_display_name']}: {e}"
                )
        self.database_manager.connection.commit()
        cursor.close()
